### ISSUE TITLE
Can't run bot with default parameters

### ISSUE THREAD

**Issue by JIy3AHKO** [pointsgame/oppai-rs#4]
Hello, 

I tried to run bot via instruction in readme:
1. cargo build --release
2. cargo run --release -s NegaScout -t 8 -g 1000
I've got this error:

`error: The argument '--moves-order <moves-order>' cannot be used with one or more of the other specified arguments`

I tried to use all combinations of Solver [UCT, NegaScout] Moves-Order [None, Random, TrajectoriesCount] parameters, but still get this error can you help me?

Thank you!

**Comment by kurnevsky** [comment]
Fixed, thanks!
btw, if you'd like to run from cargo with arguments you have to separate them with '--' like:
```
cargo run --release -- -s NegaScout -t 8 -g 1000
```
